package:
  name: itk
  version: 4.5.2

source:
  git_url: git://itk.org/ITK.git
  git_tag: v4.5.2

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python
    - numpy

test:
  # Python imports
  imports:
    - itk

about:
  home: http://itk.org/
  license: Apache 2.0 License

