package:
  name: scikit-fmm
  version: 0.0.5dev

source:
  git_url: https://github.com/scikit-fmm/scikit-fmm.git

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - distribute
    - numpy

  run:
    - python
    - numpy


test:
  # Python imports
  imports:
    - skfmm

about:
  home: https://github.com/scikit-fmm/
  license: BSD Software License

